# @package _global_
defaults:
  - base_config
  - environment: dense_forest

scene_name: "complex_forest_scene"
description: "Complex multi-species forest environment"
scene_duration: 18.0
background_noise_level: 48.0
tags: ["multi-species", "complex", "forest"]

sources:
  - audio_file: "sounds/elephant_call.wav"
    position: [120.0, 45.0, 0.0]
    start_time: 4.0
    volume_scale: 0.9
    source_type: "elephant"
  
  - audio_file: "sounds/hornbill_call.wav"
    position: [60.0, -30.0, 12.0]
    start_time: 1.0
    volume_scale: 0.7
    source_type: "bird"
  
  - audio_file: "sounds/langur_alarm.wav"
    position: [80.0, 100.0, 15.0]
    start_time: 8.0
    volume_scale: 0.8
    source_type: "monkey"
  
  - audio_file: "sounds/vehicle_distant.wav"
    position: [0.0, -400.0, 0.0]
    start_time: 0.0
    volume_scale: 0.4
    source_type: "vehicle"

ambient:
  rain:
    condition_type: "rain"
    intensity: "light"
    level_db: 32.0
  wind:
    condition_type: "wind"
    intensity: 15.0
    level_db: 28.0
  forest_base:
    condition_type: "forest_base"
    intensity: "medium"
    level_db: 30.0