# @package _global_
defaults:
  - environment: forest_clearing
  - processing: standard
  - _self_

# Basic scene parameters
scene_duration: 10.0
background_noise_level: 45.0
scene_name: "default_scene"
description: "Default acoustic scene configuration"
tags: []

# Default source for basic functionality - uses synthetic tone
sources:
  - audio_file: "test_tone.wav"
    position: [100.0, 0.0, 0.0]
    start_time: 1.0
    volume_scale: 1.0
    source_type: "elephant"

# Ambient conditions
ambient: {}

# Dataset configurations
datasets: []