# Google Drive datasets
datasets:
  - dataset_name: "Wildlife Audio Collection"
    source_type: "google_drive"
    path_or_id: "1A2B3C4D5E6F7G8H9I0J"  # Google Drive folder ID
    audio_extensions: [".wav", ".mp3", ".m4a"]
    metadata_file: "collection_metadata.csv"
    cache_dir: "./audio_cache/wildlife_drive"
  
  - dataset_name: "Research Team Recordings"
    source_type: "google_drive"
    path_or_id: "your_shared_folder_id_here"
    audio_extensions: [".wav", ".flac"]
    cache_dir: "./audio_cache/team_recordings"